version: '3.7'

services:


  frontend:
    stdin_open: true
    tty: true
    build: ./client
    container_name: "client_container"
    ports:
      - 3000:3000
    environment:
      CHOKIDAR_USEPOLLING: "true"

#  mongo:
#    image: mongo:bionic
#    restart: always
#    container_name: 'mongo_container'
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: admin
#      MONGO_INITDB_ROOT_PASSWORD: admin
#      MONGO_INITDB_DATABASE: db
#    volumes:
##      - mongo-volume:/data/db
#      - ./mongodb-setup.js:/docker-entrypoint-initdb.d/mongodb-setup.js:ro
#    ports:
#      - 27017:27017

  backend:
    build: ./server
    restart: always
    environment:
      CHOKIDAR_USEPOLLING: "true"
    container_name: "server_container"
#    environment:
#      DATABASE_URL: mongodb://admin:admin@mongo:27017/
#    volumes:
#      - ./server/uploads:/uploads
#    links:
#      - mongo:mongo
    ports:
      - 5000:5000

  nginx:
    image: nginx:alpine
    depends_on:
      - backend
      - frontend
    container_name: proxy-app
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: always

#volumes:
#  mongo-volume:
#    driver: local