version: '3.7'

services:
  frontend:
    stdin_open: true
    tty: true
    build: ./client
    container_name: "client_container"
    ports:
      - '3000:3000'
    environment:
      PORT: 3000

  mongo:
    image: mongo:bionic
    restart: always
    container_name: 'mongo_container'
    environment:
      MONGO_USERNAME: admin
      MONGO_PASSWORD: admin
    volumes:
      - mongo-volume:/data/db
    ports:
      - '27017:27017'


  backend:
    build: ./server
    restart: always
    container_name: "server_container"
    environment:
      DATABASE_URL: mongodb://admin:admin@mongo:27017/
    volumes:
      - ./server/uploads:/uploads
    links:
      - mongo:mongo
    ports:
      - "5000:5000"

volumes:
  mongo-volume:
    driver: local